import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/providers/next-auth-provider";
import GlobalProvider from "@/contexts";

export const metadata: Metadata = {
  title: "SnapStory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Plus+Jakarta+Sans:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="">
        <NextAuthProvider>
          <GlobalProvider>
            <Navbar />
            {children}
          </GlobalProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
