import type { Metadata } from "next";
import "./globals.css";
import NextThemerProvider from "@/providers/theme-provider";
import NextAuthProvider from "@/providers/next-auth-provider";
import GlobalProvider from "@/contexts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <NextThemerProvider>
          <NextAuthProvider>
            <GlobalProvider>{children}</GlobalProvider>
          </NextAuthProvider>
        </NextThemerProvider>
      </body>
    </html>
  );
}
